{
    name = "eelygoodsite"
    compatibility_date = "2025-12-19"

    "main": "dist/_worker.js/index.js",

    [[routes]]
    pattern = "shop.example.com"
    custom_domain = true

    [assets]
    directory = "./dist"
    "compatibility_flags": [
    "nodejs_compat",
    "global_fetch_strictly_public"
  ],
  "assets": {
    "binding": "ASSETS",
    "directory": "./dist"
  },
  "observability": {
    "enabled": true
  }
}

